export default  {
    black: '#000',
    white: '#fff',
    transparent: 'transparent',
    shadow: 'rgba(0, 0, 0, 0.3)',
    primary: '#06F',
    primaryDark: '#06C',
    success: '#0C3',
    successDark: '#0C0',
    danger: '#F00',
    dangerDark: '#C00',
    warning: '#FC6',
    warningDark: '#FC3',
    default: '#FFF',
    defaultDark: '#CCC',
    yellow: '#FFCC33',
    yellowDark: '#CC9900',
    whites: ['#fff', '#eee', '#cfcfcf'],
    blacks: ['#777', '#666', '#5f5f5f']
};